version: "3"

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kotol_db
  web:
    build: .
    command: 
      - alembic 
      - run
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

