"""v0.4

Revision ID: 0975ab0b13f2
Revises: fa4bd72978dc
Create Date: 2023-04-11 22:51:34.033801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0975ab0b13f2'
down_revision = 'fa4bd72978dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boiling', sa.Column('recipe_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boiling', 'recipe_name')
    # ### end Alembic commands ###
