"""v0.5

Revision ID: 8ec230af7434
Revises: 0975ab0b13f2
Create Date: 2023-04-11 22:52:28.634116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec230af7434'
down_revision = '0975ab0b13f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boiling', 'recipe_name')
    op.add_column('products', sa.Column('actual_recipe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'actual_recipe')
    op.add_column('boiling', sa.Column('recipe_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
